# Generated by Django 5.1.1 on 2024-11-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_no', models.IntegerField()),
                ('train_name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('starting_from', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('food_supply', models.BooleanField(default=False)),
                ('sleeper_price', models.IntegerField()),
                ('general_price', models.IntegerField()),
                ('ac_price', models.IntegerField()),
                ('sleeper_seats', models.IntegerField()),
                ('general_seats', models.IntegerField()),
                ('ac_seats', models.IntegerField()),
            ],
        ),
    ]
