# Generated by Django 5.1.1 on 2024-11-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customapiapp', '0002_rename_trains_train'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
